### ISSUE TITLE
Redesigning Website 

### ISSUE THREAD

**Issue by uaemmcgill** [uaem-na/donations-tracker#103]
After some discussion, the business team realized that some changes should be made to the web-design so that users can navigate through the website more easily. Basically, we think that the links/buttons that appear under the circle icon on the top right should be moved elsewhere ("Make an Offer", "Make a Request", "Your account").

1. Move the "Make an Offer" and "Make a Request" to the top of the "Posts" page (instead of appearing once the user clicks on the circle icon on the top right).
2. Move the "Your Account" page to be under "Home" in the menu bar on the left. Rename the page to "Account"

**Comment by shjryan** [comment]
Closing due to not enough time.
