### ISSUE TITLE
Preventing Profane Language 

### ISSUE THREAD

**Issue by uaemmcgill** [uaem-na/donations-tracker#104]
Is there a way to prevent the use of profane language on this website? Right now, users can use such language on offers/requests and user Display Name.

What the business team can do is come up with a list of profane terms/phrases which can be used to automatically prevent those posts/Display names.

**Comment by shjryan** [comment]
Yes, we can filter out profanity upon saving a post or for users' display names.
Please provide the terms/phrases, and we will make it an issue devs can work on.

**Comment by uaemmcgill** [comment]
Here is a folder that includes a text document with all the profane words we would like restricted for user's display names. 

[facebook-bad-words-list_comma-separated-text-file_2022_05_01.zip](https://github.com/uaem-na/donations-tracker/files/13537970/facebook-bad-words-list_comma-separated-text-file_2022_05_01.zip)

**Comment by shjryan** [comment]
Resolved by #123
