### ISSUE TITLE
Account Deactivation Process

### ISSUE THREAD

**Issue by uaemmcgill** [uaem-na/donations-tracker#107]
When an account is deactivated, the user should be notified by their account’s e-mail address immediately (as soon as the account is deemed deactivated by the admins)
The e-mail should include the following: 
- Reason for deactivation (Numerous reports, inappropriate language, fake/scams)
- List of restrictions put on their account due to it being deactivated
- Steps showing how to possibly reactivate their account 
- Admin/account support contact info (e-mail) 

Restrictions placed on an account that has been deactivated should include: 
- User will be unable to login to their account (login screen will prompt "This account has been deactivated, see why?” link on attempt to login)
- User will not be able to make offers and requests
- User's offers/requests that were posted before the account deactivation will be removed/hidden from the public 
**Note** We also want to limit the contact that the deactivated account has with other users (possibly by sending an e-mail to the users that were/are in contact with the newly deactivated account)

Process of Reactivation 
- Deactivated user will have the opportunity to contact the admins/account support e-mail to explain why their account should be re-activated or why reason for deactivation is misinterpreted/unreasonable
- Admins will then reconsider/review why the deactivated account was deactivated and decide whether it will be reactivated
- If/when the account is reactivated, user will regain all previously disabled actions

**Comment by shjryan** [comment]
Will create email notification system. Then we can proceed with this issue.

**Comment by shjryan** [comment]
Resolved by #139
