### ISSUE TITLE
"Other" Posts Process

### ISSUE THREAD

**Issue by uaemmcgill** [uaem-na/donations-tracker#112]
When an account is trying to make a post using the "_other_" category, the user's post will be sent to a post inbox only accessible by admins. 
The post will then have a list of restrictions put upon it until approved by admins (done to ensure that the item being offered/requested is appropriate). The restrictions acted on the "_other_" category post will include the following: 

- Post is hidden from the public posts page
- Post will be inaccessible
- The public/other users will not be able to interact with the pre-approved "_other_" post (excluding admins)
- Post will not show up on the map located on the "home" page 

The user will also be notified that their post is awaiting approval through e-mail (to ensure that there is no confusion as to where their post went). The e-mail will include the following:

- Description of where their post has gone/why it is not public
- Explanation of why this precaution was taken for posts made with the "_other_" category 

If/when the post gets approved by the admins the following will occur: 

- The previously mentioned restrictions will be removed
- The user that made the post will be notified by e-mail that their post has been approved and has been made open to the public

If the "_other_" category post is disapproved, the following will occur:

- The post will be flagged and removed (thus permanently inaccessible/hidden from the public)
- The user that made the original "_other_" category post will be contacted through e-mail and told that their post has been disapproved and removed by the admins
- A short explanation as to why the user's post was disapproved will be attached to the e-mail

**Comment by shjryan** [comment]
@uaemmcgill Can we use a generic reason to disapprove posts? I think users can follow up if they have questions.
