### ISSUE TITLE
French Translation to be added on Donations Tracker Website 

### ISSUE THREAD

**Issue by uaemmcgill** [uaem-na/donations-tracker#125]
Here are the French versions of the "FAQ" and "About us" sections that need to be added to the Donation Tracker website. 

FAQ French Translation (English question is bolded, not to be included with the translation): 

**How is Donations Trackers different from other product-sharing websites?**
Comment  le “Donations Trackers” se distingue-t-il des autres sites web d’échange de produits?
Bien qu’il existe l’option de vendre/acheter des produits sur ce site web,  le “Donations Trackers” se distingue des autres sites d’achat en ligne puisqu'il encourage le partage de dons. L'équipe de développement a réalisé qu’en dépit du grand nombre de platformes pour vendre/acheter des produits, il existe un manque de sites internet favorisant les dons. En rendant les dons plus accessibles, le “Donations Trackers” espère d’améliorer le moral et le bien-être de la communauté 

**What is the difference between registering as an individual vs. organization?**
Quelle est la différence entre s’inscire en tant qu’individu et en tant qu’organisation? 
S’inscrire en tant qu’individu ne nécessite pas que l’utilisateur soit associé à une organisation (par exemple, ONG, entreprise). Il n’y a pas de restrictions géographiques pour les utilisateurs indidvuels (c’est-à-dire que les utilisateurs indidvuels n’ont pas besoin de vivre dans la ville de Montreal). Cependant, les utilisateurs indidividuels ne peuvent proposer des dons/produits (sans faire de demandes). S’inscrire en tant qu’organisation rend obligatoire l’association de l’utilisateur avec une organisation légitime. La légitimité de l’;organisation sera approuvée par les administrateurs du site lors de l’inscription. Pour l’instant, il est requis que l’organisation soit basée dans la ville de Montreal à des fins du site. Les utilisateurs d’organisations peuvenet faire des offres et des demandes. 

**How can users be sure that the website is secure?**
Comment les utilisateurs peuvent-ils être sûrs que le site web est sécurisé?
En tant que groupe d’étudiants universitaires créant ce site web, nous comprenons que la sécurité de cette site pourrait susciter des interrogations. Notre équipe de développement web a travaillé ardemment pour garantir que votre vie privée et vos informations d’authentificiation soient gérées en toute sécurité sur notre site web. Certains des moyens que nous avons mis en oeuvre pour vous assurer une expérience sûre et sécurisée sont énumérés ci-dessous:
Si un utilisateur s’inscrit en tant qu’organisation, les administrateurs du site web passerent par un processus d’authentification obligatoire pour s’assurer que l’organisation est légitime. Seulement après cela, l’inscription sera complétée et l’utilisateur pourra utiliser le site web.
Si vous avez des doutes raisonables concernant la fiablité ou la légitimité d’un autre utilisateur vous pouvez les signaler en cliquant sur le bouton “Signaler l’utilisateur”, qui se trouve sur “TBD”. Une fois qu’un utilisateur a été signalé, son activité sera temporarirement bloquée jusqu’à ce que les administrateurs du site web effectuent une vérification de l’arrière-plan. 

**If there are issues/errors with donations or monetary transactions, what should we do?**
En cas de problèmes ou d’erruers liés aux dons ou aux transactions monétaires, que devrions-nous faire? 
Nous comprenons parfatiement que des problèmes liés aux dons ou aux transactions peuvenet survenir en raison de diverses causes (par exemple, des difficultés techniques). Donations Trackers n’est pas responsables des erreurs ou problèmes survenant lors d’une transaction ou d’un don. Ces erreurs ou problèmes comprennent, mais ne sont pas limités à: 
Dommages aux produits - Nouse vous encourageons à vérifier que tous les produits sont dans l‘état souhaité avant de finaliser la transaction/don
Produits qui sont différents de leur description sur le site web - Nous vous encourageons à vérifier que tous les produits correspondent à leur description sur le site web
Non-réception des frais après la vente du produit 
Erreur liées aux transactions - Veuillez contacter la banque correspondante pour toute erreur liée aux transactions monétaires 
Si vous rencontrer des problèmes avec un utilisateur spécifique pendant une don/transaction, veuillez les signaler dès que possible en utilisant la fonction “Signaler l’utilisateur”, afin que l’activité de l’utilisatuer puisse être temporairement bloquée. Donations Trackers vous remercie de votre comréhension et de votre coopération. 
Si vous avez d’autres questions ou préoccupations, veuillez envoyer un courriel à [ueam@ssmu.ca](mailto:ueam@ssmu.ca)

About us French Translation: 

UAEM est un réseau mondial d'étudiants universitaires qui s'efforcent d'accroître l'accès et l'abordabilité aux médicaments vitaux. Considérant que les universités sont des acteurs clés dans le pipeline de développement des médicaments, les étudiants peuvent promouvoir des pratiques de licence équitables en encourageant des changements de politique universitaire. Le chapitre UAEM de McGill est l'un des chapitres les plus actifs en Amérique du Nord. Actuellement, les principaux projets du chapitre incluent Donations Trackers, ainsi que le Bulletin Canadien de l'UAEM, la Science Ouverte, et plus encore.

Courriel : uaem@ssmu.ca
Facebook : UAEMMcGill
Instagram : @uaem_mcgill

À propos de nous
Le ‘’Donations Trackers’’ a été développé par des membres des Universités Alliées pour les Médicaments Essentiels (UAEM) et un groupe dévoué de développeurs web étudiants à l'Université McGill.

Donations Trackers
Le ‘’Donations Trackers’’ est un site web qui fournit une plateforme permettant aux utilisateurs de partager efficacement et efficacement des dons dans la région du Grand Montréal. Le projet a été conçu par un groupe de membres de l'UAEM McGill au cours d'un sprint de conception appelé Innovate4Health organisé par ReAct, l'IFMSA (Fédération Internationale des Associations d'Étudiants en Médecine) et l'Initiative IDEA à l'École de Santé Publique Bloomberg de Johns Hopkins. À l'origine, le site web visait à augmenter la transparence dans la distribution de l'équipement de protection individuelle (EPI) en période de pénurie pendant la pandémie de COVID-19. Avec la pandémie qui se termine progressivement (et heureusement), l'équipe a décidé d'adapter le site web pour augmenter l'accessibilité aux dons/réceptions en général (par exemple, nourriture en conserve, biens essentiels, vêtements usés, etc.).

**Comment by shjryan** [comment]
@youngsun4786 hey, double checking, did we add all these resources with #137 ?

**Comment by youngsun4786** [comment]
> @youngsun4786 hey, double checking, did we add all these resources with #137 ?

yep!, They have been all added for faq and about-us page

**Comment by shjryan** [comment]
Closed with PR #137 & PR #138
