### ISSUE TITLE
Pages 

### ISSUE THREAD

**Issue by uaemmcgill** [uaem-na/donations-tracker#20]
I've started a Figma document with the desired pages/design of the website. I'll also describe some in words below.
Figma: [https://www.figma.com/file/gfy3OdNXAnNhsJCijCZ4Iw/Donations-Trackers?type=design&node-id=0%3A1&t=Sergmv4JRwW8N8Cm-1](url) 
I can also directly share with you the document if that's easier. 

Here are the pages that we would like listed on top of the website:
**Home**
- This page will show the virtual map (i.e. can remain as is). 

**Login or My Account**
- Before the user logs in, the page would be the Login page (which can remain as is).
- After the user logs in, I think it would only make sense that the page changes to a My Account page. This page would contain the Dashboard, Account Information, and buttons linking to the Make Offer and Make Request pages (please see the Figma page, as I think it provides a more clear description of what I mean visually). 

**Offers**
- This page will contain a list of offers (donations or selling). I think we can make this page visible to registered and non-registered users. Showing this page to non-registered users (i.e. didn't log in) could act as an incentive for them to sign up.
- I'm working on the design of the page on Figma at the moment, but I'm imagining it'll just be a database of offers users can filter/search within. 

**About**
- This page will contain information about the Donations Trackers website, UAEM (including McGill UAEM), and the web developers (i.e. contributor's list). 
- This page will be visible whether the user logged in or not. 
- The working draft for the page is here (also linked on Figma): [https://docs.google.com/document/d/1T-DGY9uXOf196XrLhmHNVJSudU2AgEKgMiXFi1SEKRA/edit?usp=sharing](url)

**FAQ**  
- This page is the FAQ page. 
- This page will be visible whether the user logged in or not. 
- This working draft for the page is here (also linked on Figma): [https://docs.google.com/document/d/1AukdPBtELDP5Ehyyulmrf98ZtIK93BbhV-L1qjxuuFQ/edit?usp=sharing](url)

**Comment by shjryan** [comment]
@uaemmcgill do we have any idea on what information will be displayed on dashboard?

**Comment by uaemmcgill** [comment]
@shjryan I'm not too sure what the initial intent of the Dashboard was when our previous web-devs were creating the website. I'm assuming it would be a table (something like an embedded database table) of all of the requests and offers the user is interested in, which we showed in our initial presentation of the website to the web devs (as seen below). 

<img width="717" alt="Screen Shot 2023-06-13 at 2 55 34 PM" src="https://github.com/uaem-na/donations-tracker/assets/134973789/d6200062-fc53-42b9-b9d9-699c1eccc8b6">

@Lucas44 Do you know what the purpose was for the Dashboard?

**Comment by shjryan** [comment]
#26 adds prototype user sign up flow
#27 adds about page
#28 adds FAQ page

**Comment by shjryan** [comment]
@uaemmcgill Thanks. We will need to create this dashboard from scratch. Do you want to stick with that lingo (Receivers & Distributors) and the look & feel?
