### ISSUE TITLE
Individual Users can Request 

### ISSUE THREAD

**Issue by uaemmcgill** [uaem-na/donations-tracker#68]
From our previous discussion, we decided that individual users would only be allowed to offer products/donations.
However, right now individual users can make requests. 

- "Make a request" is available. 
- "My posts" has "Requests" tab. 

<img width="231" alt="Screen Shot 2023-09-19 at 7 33 53 PM" src="https://github.com/uaem-na/donations-tracker/assets/134973789/1ed06705-bef8-4f7b-9a24-d42d47f2ce2d">
<img width="1005" alt="Screen Shot 2023-09-19 at 7 34 04 PM" src="https://github.com/uaem-na/donations-tracker/assets/134973789/8cf0a4cc-31d3-484b-bc00-10ce4d312712">

We can either eliminate these options altogether for individual users. Or, when the individual user clicks on those features, we can have a pop-up saying this is only allowed for organization users. I don't mind which option we go with.

**Comment by shjryan** [comment]
Closing in favour of #77
