### ISSUE TITLE
Map not Loading on each Offer and Request post

### ISSUE THREAD

**Issue by uaemmcgill** [uaem-na/donations-tracker#72]
<img width="468" alt="Screen Shot 2023-09-19 at 7 51 37 PM" src="https://github.com/uaem-na/donations-tracker/assets/134973789/f7dd02e0-5d7d-4a8f-9b48-56b222363902">

The map is not loading for the individual Offer and Request posts. I've tried this with a random postal code (may not exist) and a valid postal code in Montréal (H3A 2B4 and H3A2B4, i.e. with and without space).

**Comment by shjryan** [comment]
This most likely has something to do with geocoding postal code not working properly, and thus the app is unable to display the proper coordinates (?). New issue will be created once confirmed.

Potentially blocks: If location information is invalid when creating a post, alert the user that it is invalid, and prevent post creation

**Comment by iam-weijie** [comment]
The map is present and working for the individual Offer and Request posts (just zoom out to see the full map). However, with each new post created (with postal codes like H3A2B4, without space), its coordinates are set automatically to [0,0], resulting in the map pointing into the Atlantic Ocean. Most likely has something to do with api not working properly, and thus the app is unable to fetch the proper geocoded coordinates.

P.S. I've tried to create posts with space in between the postal codes, there is the presence of an alert about invalid postal codes and prevention of post creation as a result.

**Comment by shjryan** [comment]
Resolved on GCP.
