### ISSUE TITLE
Organization Sign-up Issue 

### ISSUE THREAD

**Issue by uaemmcgill** [uaem-na/donations-tracker#73]
I can't register as an organization, because the website won't allow me to input an address at all. I can input a postal code, but not an address, so I can't test the website as an organization. 

Also, same question here regarding the postal code format issue - do we want to restrict the postal code input format? 
#71

**Comment by uaemmcgill** [comment]
<img width="544" alt="Screen Shot 2023-09-19 at 7 57 28 PM" src="https://github.com/uaem-na/donations-tracker/assets/134973789/0fa87370-ba30-447d-905e-4b2c45f937c2">

**Comment by shjryan** [comment]
Closing in favour of #85
