### ISSUE TITLE
Mobile Display: Contact information not being displayed on posts

### ISSUE THREAD

**Issue by uaemmcgill** [uaem-na/donations-tracker#76]
For Request and Offer posts, the contact information of the author isn't being displayed on the mobile version of the website. 
![IMG_9892 2](https://github.com/uaem-na/donations-tracker/assets/134973789/7e83998f-10b1-43ce-842b-a63e3eed41db)

**Comment by shjryan** [comment]
I think this is intended as we only display email address when a user is logged in. Feel free to reopen this issue if this is not the case.
