### ISSUE TITLE
Update FAQ Page with New Content

### ISSUE THREAD

**Issue by shjryan** [uaem-na/donations-tracker#84]
## Description

As per the request from the business team, we need to update the FAQ page with new content provided by them.

## Expected Actions

1. Review the new content provided by the business team.
2. Update the existing FAQ page with the new questions and answers.
3. Format the content to maintain consistency with the overall design of the FAQ page.
4. Ensure that the navigation and layout of the FAQ page are user-friendly and intuitive.
5. Test the updated FAQ page to verify that the new content displays correctly and is accessible (keyboard navigation) to users.

**Comment by shjryan** [comment]
@uaemmcgill need your input.

**Comment by uaemmcgill** [comment]
The business team will have a meeting this coming Monday to discuss this. We'll write up an updated version of the FAQ afterwards and give it to you guys!

**Comment by uaemmcgill** [comment]
I apologize for the delay! We are still working on the draft for the FAQ page. We'll get it to you asap!

**Comment by uaemmcgill** [comment]
Here is the updated content for the FAQ page! https://docs.google.com/document/d/1AukdPBtELDP5Ehyyulmrf98ZtIK93BbhV-L1qjxuuFQ/edit?usp=sharing

Three new questions were added (the first three), and I've commented on them. 
The new content was written based on the new web design that was requested in issue #103 .
