### ISSUE TITLE
Update Admin Pages with Clear Usage Instructions

### ISSUE THREAD

**Issue by shjryan** [uaem-na/donations-tracker#87]
## Description

Update admin pages with clear and comprehensive usage instructions. These instructions should guide administrators on how to effectively use the various features and functions available on these pages.

## Task Details

1. Admin Pages: We have several admin pages in our open source web application, each with its unique set of features and controls.

## Expected Actions

* Review each admin page to understand its functionality and features thoroughly.
* Create clear and user-friendly instructions for each admin page, covering the following:
* Overview of the page's purpose and features.
* Step-by-step instructions on how to perform common tasks or actions.
* Explanation of any advanced settings or options.
* Guidance on best practices and recommended workflows.
* Integrate the instructions directly within each admin page, ensuring that they are easily accessible to administrators.

**Comment by youngsun4786** [comment]
@shjryan @uaemmcgill I've spent bit of time looking at the code base and figuring out the detailed functionality and features each admin page serves, however, I wanted to clarify whether the understanding for a particular page is correct.

<img width="1335" alt="Screenshot 2023-11-01 at 10 04 31 PM" src="https://github.com/uaem-na/donations-tracker/assets/83793112/949b4f96-5ef3-4f5e-91ee-4af865f69f83">


For the `/admin/post` page, it's purpose seems to be to view new posts made by users and approve or reject them before displaying them on public. I'd like validate some things to prevent any further misunderstandings, if there's anything I am missing that you wish to add please let me know!

**Comment by shjryan** [comment]
@youngsun4786 Hi Nick! Thank you for working on this issue.

`/admin/post` page should be the place for admins to approve posts before they go live for posts that have category set to "other". Not all posts will show up here.

**Comment by ChrisL2408** [comment]
@shjryan Hey just wanted to confirm that @youngsun4786 is still working on this issue? For some reason, this issue is on our board wondering if it shouldn't be? Thanks!

**Comment by youngsun4786** [comment]
@astroboi556  Hey I just saw your comment, I forgot to change the status to In Progress while working. I am almost complete with this issue so I'll ping for PR ASAP.

**Comment by youngsun4786** [comment]
@shjryan I have a quick question regarding the posts page, as you know, there are two post pages admin can access and one of them is followed by the admin keyword in the route path. However, I noticed that the posts page under admin route and posts page without admin both uses the same `postsContainer` and `FilterLayout` component  under `src/components/Posts`. Is there a way to distinguish the two posts (i.e do backend apis return a boolean value for instance to separate the two) or should I be passing in a boolean value as a prop from  posts component that is under `admins/posts` ?
