### ISSUE TITLE
Create a Reusable Toast Notification Component

### ISSUE THREAD

**Issue by shjryan** [uaem-na/donations-tracker#90]
## Description

Create a reusable toast notification component that can be utilized on any page. This component will enhance user communication and user experience by providing a consistent way to display notifications across the application.

## Issue Details

1 Toast Notification Component: We need to develop a versatile toast notification component that can be easily integrated into any page within our application.

## Expected Behavior

The toast notification component should allow developers to display notifications with various types (success, error, info, etc.) and duration. It should be designed for reusability and customization. This should also utilize hooks or context. The toast notifications should be stackable.

## Additional Context

A reusable toast notification component simplifies the process of notifying users about events or actions within our application, ensuring a consistent and user-friendly experience.

## Acceptance Criteria

* The toast notification component should be created, providing a standardized way to display notifications.
* Developers should be able to customize the content, type, and duration of notifications using the component.
* Documentation should be provided in the component code file on how to use the component.

## Implementation Guidelines

* Develop the toast notification component with appropriate props for customization.
* Ensure that the component is easily integratble into any page.
* Provide documentation and examples on how to use the component.

**Comment by ChrisL2408** [comment]
@shjryan Can I remove this from the Hack4Impact board or is @Deniz-x on your team working on this issue? thanks!

**Comment by ChrisL2408** [comment]
@shjryan Just wondering on this ticket if Deniz is still working on it?

**Comment by shjryan** [comment]
I will reach out to Deniz and update here.
