### ISSUE TITLE
User Report History Viewing

### ISSUE THREAD

**Issue by shjryan** [uaem-na/donations-tracker#94]
## Description

Allow users to view their history of reports. This read-only feature provides users with transparency into their reporting activity, enhancing their experience and accountability on our platform.

## Issue Details

1. User Report History: Currently, our application lacks a dedicated feature for users to view their history of reports.

## Expected Behavior

Users should have the ability to access and view their report history. This feature allows users to see a list of reports they've submitted in the past, promoting transparency and accountability.

## Acceptance Criteria

* Implement a feature that allows users to view their history of reports.
* The report history page should be read-only, meaning users can view the reports they've submitted but cannot modify them.
* Users should be able to access their report history from their profile or account settings.

## Implementation Guidelines

* Create a user-friendly interface for accessing the report history.
* Develop the logic to retrieve and display the user's report history.
* Ensure that the report history is presented in a clear and organized manner.

**Comment by ChrisL2408** [comment]
@shjryan is it ok if i remove this issue from the uaem x mcgill board?

**Comment by shjryan** [comment]
@ChrisL2408 sure!
